# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a220216a87e8993d9c85fdb428c9457df2547d918cccb12f6a02c6b04065fc2528707a2aeb0c61682e1530cfd1510edcea2b734b236b630efd8d1a47a2794f61

test:
  secret_key_base: 669ef1cf0eb5223a580c559de318e2764e43e6b827495cae23de9a989b7891f35334e06fdd9155e6ed4446a4b3441f09ab600fadd646da934c8c0450aebe4f89

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
